const products = [
	{
		_id: '1',
		name: 'Jogger Pant',
		image: '/images/product1.jpg',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias labore doloremque aliquam a, animi nobis repellat porro perferendis.',
		brand: 'Moose',
		category: 'Men',
		price: 2350.0,
		countInStock: 10,
		rating: 4.5,
		numReviews: 12,
		size: [{ size: 'L' }, { size: 'XL' }],
	},
	{
		_id: '2',
		name: 'Cascais Shirt',
		image: '/images/product2.jpg',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias labore doloremque aliquam a, animi nobis repellat porro perferendis.',
		brand: 'Moose',
		category: 'Men',
		price: 2350.0,
		countInStock: 7,
		rating: 4.0,
		numReviews: 8,
		size: [{ size: 'M' }, { size: 'XL' }],
	},
	{
		_id: '3',
		name: 'Vila Nova Shirt',
		image: '/images/product3.jpg',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias labore doloremque aliquam a, animi nobis repellat porro perferendis.',
		brand: 'Moose',
		category: 'Men',
		price: 2350.0,
		countInStock: 5,
		rating: 3,
		numReviews: 12,
		size: [{ size: 'M' }, { size: 'L' }],
	},
	{
		_id: '4',
		name: 'Cotton Shorts',
		image: '/images/product4.jpg',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias labore doloremque aliquam a, animi nobis repellat porro perferendis.',
		brand: 'Moose',
		category: 'Men',
		price: 2350.0,
		countInStock: 11,
		rating: 5,
		numReviews: 12,
		size: [{ size: 'XL' }],
	},
	{
		_id: '5',
		name: 'Denim Shorts',
		image: '/images/product5.jpg',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias labore doloremque aliquam a, animi nobis repellat porro perferendis.',
		brand: 'Moose',
		category: 'Men',
		price: 2350.0,
		countInStock: 7,
		rating: 3.5,
		numReviews: 10,
		size: [{ size: 'L' }],
	},
	{
		_id: '6',
		name: 'Sports T-Shirt',
		image: '/images/product6.jpg',
		description:
			'Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias labore doloremque aliquam a, animi nobis repellat porro perferendis.',
		brand: 'Moose',
		category: 'Men',
		price: 2350.0,
		countInStock: 0,
		rating: 4,
		numReviews: 12,
		size: [{ size: 'L' }, { size: 'XL' }],
	},
];

export default products;
